import { cache } from "react"
import type { SanityImageSource } from "@sanity/image-url"

import { urlFor } from "@/sanity/lib/image"
import { sanityFetch } from "@/sanity/lib/live"
import { HOME_PAGE_QUERY, SITE_SETTINGS_QUERY } from "@/sanity/lib/queries"
import { HOME_DEFAULTS, SITE_DEFAULTS, type HomeContent, type SiteContent } from "./defaults"
import { withFallback } from "./merge"

export type ShareImage = { url: string; alt: string; width: number; height: number }

export const SHARE_IMAGE_SIZE = { width: 1200, height: 630 }

const MIN_SHARE_IMAGE_WIDTH = 600

// Generated by app/share-image.png/route.tsx; used until an image is set in Sanity
const FALLBACK_SHARE_IMAGE: ShareImage = {
  url: "/share-image.png",
  alt: "OurProps property record showing a mapped boundary and document statuses",
  ...SHARE_IMAGE_SIZE,
}

// The site must still render if Sanity is unreachable or a document is missing,
// so every read falls back to the built-in copy.

export const getHomeContent = cache(async (): Promise<HomeContent> => {
  try {
    const { data } = await sanityFetch({ query: HOME_PAGE_QUERY, stega: false })
    return withFallback(HOME_DEFAULTS, data)
  } catch (error) {
    console.error("Failed to load homepage content from Sanity", error)
    return HOME_DEFAULTS
  }
})

export const getSiteContent = cache(async (): Promise<SiteContent & { shareImage: ShareImage }> => {
  try {
    const { data } = await sanityFetch({ query: SITE_SETTINGS_QUERY, stega: false })
    const ogImage = (
      data as { ogImage?: SanityImageSource & { asset?: unknown; alt?: string; width?: number } } | null
    )?.ogImage
    // A small image (e.g. a logo) would be blown up and cropped, so keep the generated one instead
    const useSanityImage = Boolean(ogImage?.asset) && (ogImage?.width ?? 0) >= MIN_SHARE_IMAGE_WIDTH

    return {
      ...withFallback(SITE_DEFAULTS, data),
      shareImage: useSanityImage && ogImage
        ? {
            url: urlFor(ogImage).width(SHARE_IMAGE_SIZE.width).height(SHARE_IMAGE_SIZE.height).fit("crop").url(),
            alt: ogImage.alt || FALLBACK_SHARE_IMAGE.alt,
            ...SHARE_IMAGE_SIZE,
          }
        : FALLBACK_SHARE_IMAGE,
    }
  } catch (error) {
    console.error("Failed to load site settings from Sanity", error)
    return { ...SITE_DEFAULTS, shareImage: FALLBACK_SHARE_IMAGE }
  }
})
