import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./_components/client-wrapper";
import Header from "./(marketing)/_components/header";
import Footer from "./(marketing)/_components/footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <ClientWrapper>
          <div className="flex-1">
            {children}
          </div>
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
